runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyA57RQplHvLNPfjrTTWMaEpUf-3PgwGNuU

handlers:

  - url: /
    static_files: dist/littleangels/index.html
    upload: dist/littleangels/index.html
  - url: /
    static_dir: dist/littleangels

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE