runtime: python27
api_version: 1
threadsafe: true
env_variables:
  API_KEY: AIzaSyCcJX4KIijB288dg9xnJbhFJgXyGpp9Y98

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /
  static_dir: dist